### ISSUE TITLE
[Android]抓m3u8后,保存历史后打开历史出现界面异常的问题

### ISSUE THREAD

**Issue by QAQQL** [wanghongenpin/network_proxy_flutter#113]
**描述错误**
1.0.7
抓m3u8后,保存历史后打开历史出现界面异常的问题
且导出har失败(无操作反馈,界面可切换)

**To Reproduce**
抓包wx的小鹅通直播课程

**屏幕截图*
稍后补充调试信息和界面图片

**Comment by QAQQL** [comment]
```shell
2024-01-19 09:27:52.283 20039-20067 flutter                 com.network.proxy                    I  FormatException: Invalid radix-10 number (at character 1)
                                                                                                    //wss.im.qcloud.com/binfo?sdkappid=1400505419&instanceid=4e547d8e9e33d159f5...
                                                                                                    ^
2024-01-19 09:27:52.283 20039-20067 flutter                 com.network.proxy                    I  FormatException: Invalid radix-10 number (at character 1)
2024-01-19 09:27:52.283 20039-20067 flutter                 com.network.proxy                    I  //wss.im.qcloud.com/binfo?sdkappid=1400505419&instanceid=4e547d8e9e33d159f5...
2024-01-19 09:27:52.283 20039-20067 flutter                 com.network.proxy                    I  ^
2024-01-19 09:27:52.283 20039-20067 flutter                 com.network.proxy                    I  
2024-01-19 09:27:52.283 20039-20067 flutter                 com.network.proxy                    I  #0      int._handleFormatError (dart:core-patch/integers_patch.dart:126)
2024-01-19 09:27:52.283 20039-20067 flutter                 com.network.proxy                    I  #1      int._parseRadix (dart:core-patch/integers_patch.dart:152)
2024-01-19 09:27:52.283 20039-20067 flutter                 com.network.proxy                    I  #2      int._parse (dart:core-patch/integers_patch.dart:98)
2024-01-19 09:27:52.283 20039-20067 flutter                 com.network.proxy                    I  #3      int.parse (dart:core-patch/integers_patch.dart:60)
2024-01-19 09:27:52.283 20039-20067 flutter                 com.network.proxy                    I  #4      HostAndPort.of (package:network_proxy/network/host_port.dart:69)
2024-01-19 09:27:52.283 20039-20067 flutter                 com.network.proxy                    I  #5      Har.toRequest (package:network_proxy/utils/har.dart:136)
2024-01-19 09:27:52.283 20039-20067 flutter                 com.network.proxy                    I  #6      Har.readFile (package:network_proxy/utils/har.dart:95)
2024-01-19 09:27:52.283 20039-20067 flutter                 com.network.proxy                    I  <asynchronous suspension>
2024-01-19 09:27:52.283 20039-20067 flutter                 com.network.proxy                    I  #7      HistoryStorage.getRequests (package:network_proxy/storage/histories.dart:118)
2024-01-19 09:27:52.283 20039-20067 flutter                 com.network.proxy                    I  <asynchronous suspension>
2024-01-19 09:27:52.283 20039-20067 flutter                 com.network.proxy                    I  #8      _FutureBuilderState._subscribe.<anonymous closure> (package:flutter/src/widgets/async.dart:624)
2024-01-19 09:27:52.283 20039-20067 flutter                 com.network.proxy                    I  <asynchronous suspension>
```

**Comment by wanghongenpin** [comment]
V1.0.8-Beta 已经修改

https://github.com/wanghongenpin/network_proxy_flutter/releases/tag/V1.0.8-Beta

**Comment by QAQQL** [comment]
感谢
