### ISSUE TITLE
[Android] SocketException: Too many open files

### ISSUE THREAD

**Issue by PennHan** [wanghongenpin/network_proxy_flutter#127]
**描述错误(Describe the bug)**

02-01 09:21:11.921  3649  3796 E com.network.proxy.vpn.ProxyVpnThread: Too many open files
02-01 09:21:11.921  3649  3796 E com.network.proxy.vpn.ProxyVpnThread: java.net.SocketException: Too many open files
02-01 09:21:11.921  3649  3796 E com.network.proxy.vpn.ProxyVpnThread: 	at sun.nio.ch.Net.socket0(Native Method)
02-01 09:21:11.921  3649  3796 E com.network.proxy.vpn.ProxyVpnThread: 	at sun.nio.ch.Net.socket(Net.java:420)
02-01 09:21:11.921  3649  3796 E com.network.proxy.vpn.ProxyVpnThread: 	at sun.nio.ch.Net.socket(Net.java:413)
02-01 09:21:11.921  3649  3796 E com.network.proxy.vpn.ProxyVpnThread: 	at sun.nio.ch.SocketChannelImpl.<init>(SocketChannelImpl.java:128)
02-01 09:21:11.921  3649  3796 E com.network.proxy.vpn.ProxyVpnThread: 	at sun.nio.ch.SelectorProviderImpl.openSocketChannel(SelectorProviderImpl.java:60)
02-01 09:21:11.921  3649  3796 E com.network.proxy.vpn.ProxyVpnThread: 	at java.nio.channels.SocketChannel.open(SocketChannel.java:145)
02-01 09:21:11.921  3649  3796 E com.network.proxy.vpn.ProxyVpnThread: 	at com.network.proxy.vpn.ConnectionManager.createTCPConnection(ConnectionManager.kt:79)
02-01 09:21:11.921  3649  3796 E com.network.proxy.vpn.ProxyVpnThread: 	at com.network.proxy.vpn.ConnectionHandler.replySynAck(ConnectionHandler.kt:440)
02-01 09:21:11.921  3649  3796 E com.network.proxy.vpn.ProxyVpnThread: 	at com.network.proxy.vpn.ConnectionHandler.handleTCPPacket(ConnectionHandler.kt:164)
02-01 09:21:11.921  3649  3796 E com.network.proxy.vpn.ProxyVpnThread: 	at com.network.proxy.vpn.ConnectionHandler.handlePacket(ConnectionHandler.kt:64)
02-01 09:21:11.921  3649  3796 E com.network.proxy.vpn.ProxyVpnThread: 	at com.network.proxy.vpn.ProxyVpnThread.run(ProxyVpnThread.kt:69)

**To Reproduce**
重现行为的步骤: 如具体应用抓包失败，请说明软件名称以及具体操作页面

应用运行时间过长或抓取的包过多之后，会报以上错误

**屏幕截图(Screenshots)*

**Comment by PennHan** [comment]
发现可疑的报错：
02-02 05:20:21.307  5977  6058 W System.err: java.io.IOException: Too many open files
02-02 05:20:21.307  5977  6058 W System.err: 	at sun.nio.ch.FileDispatcherImpl.preClose0(Native Method)
02-02 05:20:21.307  5977  6058 W System.err: 	at sun.nio.ch.FileDispatcherImpl.preCloseImpl(FileDispatcherImpl.java:124)
02-02 05:20:21.307  5977  6058 W System.err: 	at sun.nio.ch.SocketDispatcher.preClose(SocketDispatcher.java:66)
02-02 05:20:21.307  5977  6058 W System.err: 	at sun.nio.ch.SocketChannelImpl.implCloseSelectableChannel(SocketChannelImpl.java:883)
02-02 05:20:21.307  5977  6058 W System.err: 	at java.nio.channels.spi.AbstractSelectableChannel.implCloseChannel(AbstractSelectableChannel.java:234)
02-02 05:20:21.307  5977  6058 W System.err: 	at java.nio.channels.spi.AbstractInterruptibleChannel.close(AbstractInterruptibleChannel.java:116)
02-02 05:20:21.307  5977  6058 W System.err: 	at com.network.proxy.vpn.ConnectionManager.closeConnection(ConnectionManager.kt:49)
02-02 05:20:21.307  5977  6058 W System.err: 	at com.network.proxy.vpn.ConnectionManager.closeConnection(ConnectionManager.kt:33)
02-02 05:20:21.307  5977  6058 W System.err: 	at com.network.proxy.vpn.ConnectionHandler.ackFinAck(ConnectionHandler.kt:301)
02-02 05:20:21.307  5977  6058 W System.err: 	at com.network.proxy.vpn.ConnectionHandler.handleTCPPacket(ConnectionHandler.kt:243)
02-02 05:20:21.307  5977  6058 W System.err: 	at com.network.proxy.vpn.ConnectionHandler.handlePacket(ConnectionHandler.kt:64)
02-02 05:20:21.307  5977  6058 W System.err: 	at com.network.proxy.vpn.ProxyVpnThread.run(ProxyVpnThread.kt:69)

在关闭套接字时报了文件句柄超过限制，未正常关闭导致了socket连接满了
