### ISSUE TITLE
应用崩溃

### ISSUE THREAD

**Issue by 821938089** [wanghongenpin/network_proxy_flutter#16]
java.lang.RuntimeException: Unable to start service com.network.proxy.ProxyVpnService@d93766c with Intent { act=DISCONNECT cmp=com.network.proxy/.ProxyVpnService }: f4.p: lateinit property vpnInterface has not been initialized
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4864)
	at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2254)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8247)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
Caused by: f4.p: lateinit property vpnInterface has not been initialized
	at com.network.proxy.ProxyVpnService.c(Unknown Source:6)
	at com.network.proxy.ProxyVpnService.onStartCommand(Unknown Source:17)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4846)
	... 9 more

**Comment by wanghongenpin** [comment]
在启动时允许添加VPN那，这个应该是关闭VPN时我没做判断vpnInterface是否初始化，如果同意了启用VPN，vpnInterface不可能为空

**Comment by 821938089** [comment]
你可以把app的vpn取消一下，然后打开app会瞬间崩溃

**Comment by 821938089** [comment]
java.lang.RuntimeException: Unable to start service com.network.proxy.ProxyVpnService@bef14b4 with Intent { cmp=com.network.proxy/.ProxyVpnService (has extras) }: java.lang.IllegalStateException: 无法初始化vpnInterface
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4864)
	at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2254)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8247)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
Caused by: java.lang.IllegalStateException: 无法初始化vpnInterface
	at com.network.proxy.ProxyVpnService.b(Unknown Source:70)
	at com.network.proxy.ProxyVpnService.a(Unknown Source:0)
	at com.network.proxy.ProxyVpnService.onStartCommand(Unknown Source:40)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4846)
	... 9 more

**Comment by wanghongenpin** [comment]
> 

这里vpn变量没做判断，因为不允许添加VPN，应用也没办法使用，后面做下判断，现在不影响正常使用
