### ISSUE TITLE
[Android]应用闪退

### ISSUE THREAD

**Issue by MrMoxing** [wanghongenpin/network_proxy_flutter#188]
**描述错误(Describe the bug)**

添加任意应用至黑名单列表，点击开启抓包都会闪退

**To Reproduce**

FATAL EXCEPTION: main
Process: com.network.proxy, PID: 16453
java.lang.RuntimeException: Unable to start service com.network.proxy.ProxyVpnService@821dddb with Intent { cmp=com.network.proxy/.ProxyVpnService (has extras) }: java.lang.UnsupportedOperationException: addAllowedApplication already called
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4782)
	at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2226)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:8062)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
Caused by: java.lang.UnsupportedOperationException: addAllowedApplication already called
	at android.net.VpnService$Builder.addDisallowedApplication(VpnService.java:842)
	at com.network.proxy.ProxyVpnService.j(Unknown Source:158)
	at com.network.proxy.ProxyVpnService.i(Unknown Source:52)
	at com.network.proxy.ProxyVpnService.onStartCommand(Unknown Source:62)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4764)
	... 9 more

**屏幕截图(Screenshots)*

**Comment by wanghongenpin** [comment]
同一个应用同时存在白名单和黑名单，重了

**Comment by MrMoxing** [comment]
> 同一个应用同时存在白名单和黑名单，重了

https://github.com/wanghongenpin/network_proxy_flutter/assets/81543605/7dd279e4-9be9-43a6-b815-d73dd746e7aa

并非，就算白名单没有，只要添加黑名单就闪退

**Comment by wanghongenpin** [comment]
最新包增加了应用白名单开关，这样不需要删除白名单 可自由切换
