### ISSUE TITLE
[Android]无法编译android包

### ISSUE THREAD

**Issue by burgleaf** [wanghongenpin/network_proxy_flutter#202]
**描述错误(Describe the bug)**
编译andorid包会报错this and base files have different roots，问题出在share_plus这个包里
```
Caused by: java.lang.IllegalArgumentException: this and base files have different roots: D:\developer\dart\pub\hosted\pub.flutter-io.cn\share_plus-8.0.2\android\src\main\kotlin\dev\fluttercommunity\plus\share\MethodCallHandler.kt and F:\workplace\flutter-project\network_proxy_flutter\android.
        at kotlin.io.FilesKt__UtilsKt.toRelativeString(Utils.kt:117)
        at kotlin.io.FilesKt__UtilsKt.relativeTo(Utils.kt:128)
        at org.jetbrains.kotlin.incremental.storage.RelocatableFileToPathConverter.toPath(RelocatableFileToPathConverter.kt:22)
        at org.jetbrains.kotlin.incremental.storage.ComplementarySourceFilesMap.get(ComplementarySourceFilesMap.kt:22)
        at org.jetbrains.kotlin.incremental.AbstractIncrementalCache.getComplementaryFilesRecursive(AbstractIncrementalCache.kt:219)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.doCompile(IncrementalCompilerRunner.kt:455)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileImpl(IncrementalCompilerRunner.kt:400)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileNonIncrementally(IncrementalCompilerRunner.kt:281)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile(IncrementalCompilerRunner.kt:125)
        at org.jetbrains.kotlin.daemon.CompileServiceImplBase.execIncrementalCompiler(CompileServiceImpl.kt:657)
        at org.jetbrains.kotlin.daemon.CompileServiceImplBase.access$execIncrementalCompiler(CompileServiceImpl.kt:105)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1624)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)


....
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':share_plus:compileDebugJavaWithJavac'.

```

**To Reproduce**
升级share_plus版本问题依然存在

**Comment by burgleaf** [comment]
升级share_plus包版本问题依然存在

**Comment by wanghongenpin** [comment]
这个问题是缓存版本不一致导致的，你可以删除这个包你本地所有缓存，具体原因可以去搜索，和本软件没关系
